// Auto-generated by @rangojs/router - do not edit
export const routes = {
  about: "/about",
  counter: "/counter",
  greeting: "/hello/:name",
  home: "/",
} as const;
export type routes = typeof routes;
